# Problem set and run configuration
name: "final"
n_samp: 30
stop_criterion: "n_gen"
probs: 
  - ["ZDT1", 30]
  - ["ZDT2", 30]
  - ["ZDT3", 30]
  - ["ZDT4", 10]
  - ["ZDT6", 10]
  - ["DTLZ1", 7, 3]
  - ["DTLZ2", 12, 3]
  - ["DTLZ3", 12, 3]
  - ["DTLZ4", 12, 3]
  - ["DTLZ5", 12, 3]
  - ["DTLZ6", 12, 3]
  - ["DTLZ7", 22, 3]
  - ["WFG1", 24, 3]
  - ["WFG2", 24, 3]
  - ["WFG3", 24, 3]
  - ["WFG4", 24, 3]
probs_config:
  - [250,100]
  - [250,100]  
  - [250,100]  
  - [250,100]  
  - [250,100]
  - [500,92]  
  - [500,92]  
  - [500,92]  
  - [500,92]  
  - [500,92]  
  - [500,92]  
  - [500,92]
  - [500,92]  
  - [500,92]  
  - [500,92]  
  - [500,92]
